apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ruby-server
  template:
    metadata:
      labels:
        app: ruby-server
    spec:
      containers:
        - name: ruby-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
