apiVersion: v1
kind: Service
metadata:
  name: ruby-server
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: ruby-server
