name: Helm Chart Validation

on:
  push:
    paths:
      - 'helm-chart/**'
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.0  # you can set the desired Helm version

      - name: Helm Lint
        run: |
          cd helm-chart
          helm lint .
